[DEFAULT]

# Fast smoke test config (1 episode, 1 run)
gpu = False
min_eps = 1
max_eps = 1
n_run = 1

batch_size = 1
input_type = 3
augment_state = False
rep = 1
basis = False

bin_num = 20
forier_order = 1
forier_cross_term = False
forier_double = True

critic_lr = 0.000125
actor_lr = 0.0000625
init_scale = 0.125
adam = False
adam_beta_1 = 0.995
adam_beta_2 = 0.99995

env_name = LunarLander-v2
env_tc = 2000
env_dt = 20
reward_adj = 0.012
freeze_action = 40
isEnd_zero = True
last_zero_n = 2
rest_n = 0
warm_n = 5

actor_active = True
num_critics_exc = 16
num_critics_inh = 16
num_actors_exc_pa = 8
num_actors_inh_pa = 8
entropy_reg = 0.0
weight_reg = 0.0
value_m = 4
value_b = -2
actor_m = 15
tau_n = 20.0
tau_plus = 20.0
tau_z = 20.0
tau_q = 20.0
tau_v = 100.0
targ_firing_r = 0.0
targ_firing_rate = 0.0

name = ll_placecells16k_smoke
test = False
checkpoint = model_ll_std_0.pt
test_eps = 1
test_vis = False

[USER]

